import Head from 'next/head'
import Todos from '../components/Todos'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1 className='text-2xl text-emerald-500'>Hwllo</h1>
    <Todos />
    </div>
  )
}
