import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import Footer from '../components/common/Footer'
import Header from '../components/common/Header'
import Todos from '../components/Todos'

export default function Home() {
  return (
    <div className='h-screen bg-teal-100'>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    <div className='text-center mx-48 '>
    <Todos />
    </div>
    <Footer />
    <ToastContainer />    
    </div>
  )
}
