import Head from 'next/head'
import Footer from '../components/common/Footer'
import Header from '../components/common/Header'
import Todos from '../components/Todos'

export default function Home() {
  return (
    <div className='mx-48 '>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    <div className='text-center '>
    <Todos />
    </div>
    <Footer />
    </div>
  )
}
